spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml